Add facebook logo
starboardcoop/things-app pull request #99
Opened 2021-02-01 22:59 UTC by czalucky

i did it

2021-02-02 00:41 UTC, cmilkaitis reviewed
😡
(request changes)

2021-02-02 00:42 UTC, cmilkaitis requested changes
.

2021-02-06 14:55 UTC, dillonfagan approved these changes
Looks good

2021-02-07 14:11 UTC, mdantuono commented
Approve.

2021-02-09 00:26 UTC, merged